import { jsPDF } from "jspdf";
import type { ScreeningStageCounts } from "@/lib/validators/screening";
import { computePrismaCounts } from "@/lib/screening/prisma-counts";

/** Generate a PRISMA 2020 flow diagram as PDF. */
export async function generatePrismaPDF(
  counts: ScreeningStageCounts,
  protocolTitle: string,
): Promise<Blob> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const flow = computePrismaCounts(counts);

  // Title
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("PRISMA 2020 Flow Diagram", pageWidth / 2, 20, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(protocolTitle, pageWidth / 2, 28, { align: "center" });

  // Box drawing helpers
  const boxWidth = 65;
  const boxHeight = 22;
  const centerX = pageWidth / 2;
  const leftX = centerX - boxWidth / 2;
  const rightX = centerX + boxWidth / 2 + 10;
  let y = 40;

  const drawBox = (
    x: number,
    yPos: number,
    label: string,
    count: number,
    color?: [number, number, number],
  ) => {
    if (color) {
      doc.setFillColor(...color);
      doc.roundedRect(x, yPos, boxWidth, boxHeight, 2, 2, "F");
    }
    doc.setDrawColor(100, 100, 100);
    doc.roundedRect(x, yPos, boxWidth, boxHeight, 2, 2, "S");

    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(label, x + boxWidth / 2, yPos + 8, { align: "center" });

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text(String(count), x + boxWidth / 2, yPos + 17, { align: "center" });
  };

  const drawArrow = (x: number, y1: number, y2: number) => {
    doc.setDrawColor(150, 150, 150);
    doc.setLineWidth(0.3);
    doc.line(x, y1, x, y2);
    // Arrowhead
    doc.line(x - 2, y2 - 3, x, y2);
    doc.line(x + 2, y2 - 3, x, y2);
  };

  const drawHArrow = (x1: number, x2: number, yPos: number) => {
    doc.setDrawColor(150, 150, 150);
    doc.setLineWidth(0.3);
    doc.line(x1, yPos, x2, yPos);
    doc.line(x2 - 3, yPos - 2, x2, yPos);
    doc.line(x2 - 3, yPos + 2, x2, yPos);
  };

  // Stage labels
  const drawStageLabel = (label: string, yPos: number) => {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 100, 100);
    doc.text(label.toUpperCase(), 15, yPos + 4);
  };

  // Row 1: Identification
  drawStageLabel("Identification", y);
  drawBox(leftX, y, "Records identified", flow.identified);
  y += boxHeight;
  drawArrow(centerX, y, y + 8);
  y += 8;

  // Row 2: After duplicates
  drawBox(
    leftX,
    y,
    "After duplicates removed",
    flow.identified - flow.duplicatesRemoved,
  );
  drawHArrow(leftX + boxWidth, rightX, y + boxHeight / 2);
  drawBox(
    rightX,
    y,
    "Duplicates removed",
    flow.duplicatesRemoved,
    [255, 230, 230],
  );
  y += boxHeight;
  drawArrow(centerX, y, y + 8);
  y += 8;

  // Row 3: Screening
  drawStageLabel("Screening", y);
  drawBox(leftX, y, "Records screened", flow.screened);
  drawHArrow(leftX + boxWidth, rightX, y + boxHeight / 2);
  drawBox(
    rightX,
    y,
    "Records excluded",
    flow.screeningExcluded,
    [255, 230, 230],
  );
  y += boxHeight;
  drawArrow(centerX, y, y + 8);
  y += 8;

  // Row 4: Eligibility
  drawStageLabel("Eligibility", y);
  drawBox(leftX, y, "Reports assessed", flow.eligibilityAssessed);
  drawHArrow(leftX + boxWidth, rightX, y + boxHeight / 2);
  drawBox(
    rightX,
    y,
    "Reports excluded",
    flow.eligibilityExcluded,
    [255, 230, 230],
  );
  y += boxHeight;
  drawArrow(centerX, y, y + 8);
  y += 8;

  // Row 5: Included
  drawStageLabel("Included", y);
  drawBox(leftX, y, "Studies included", flow.included, [230, 255, 230]);

  // Footer
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by VaxEvidence on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: "center" },
  );

  return doc.output("blob");
}
